### ISSUE TITLE
xp pylon showing negativ values

### ISSUE THREAD

**Issue by yuri0r** [Lothrazar/Cyclic#894]
Minecraft version & Mod Version:
minecraft 1.12.2
cyclic 1.126.8

Single player or Server:
server only

Describe problem (what you were doing / what happened):
XP values move from 0 to 1630 and when filled with 1640 XP will show -1636
from there moving up and wrapping back to negative at the same breaking point.

the picture was taken on a local server with only cyclic and forge installed. pylon ist filled with 2000 XP.
![2018-08-09_00 11 17](https://user-images.githubusercontent.com/9966894/43867245-d489fb80-9b68-11e8-9950-3fb0899be707.png)

the problem may be related to #632 as it describes a very similar behaviour.

**Comment by PrinceOfAmber** [comment]
Did you have any fluid pipes attached? Or was this just using the buttons to insert and remove exp?

**Comment by PrinceOfAmber** [comment]
Ok i started a new world, i use /xp 1630 to give myself exp.  , then i spam all the buttons to insert and remove the exp, like this? 

![exp](https://user-images.githubusercontent.com/621529/43966750-903e9908-9c77-11e8-9bb2-56b2997da424.gif)

**Comment by yuri0r** [comment]
no fluid pipes are attached only using the buttons. (probably I was not clear enough, sorry Englisch is not my native language) also for negative values to appear you need to get over 1630 xp 1640 the negative value -1636 will show but only on a server (singleplayer worlds work fine!)

did some more testing the exact value where it wraps to negative is 1639xp

also made a little video hope that helps to clarify :)
https://youtu.be/8U-1RJjYXVs

**Comment by Enilo** [comment]
I have the exact same issue on a server running All The Mods 3, with mod version 1.15.15. Can be reproduced exactly as in the video above.

**Comment by Lothrazar** [comment]
appears fixed in 1.17.10. please verify this and make a new issue if anything comes up

**Comment by yuri0r** [comment]
sorry for the late reply, just tested with the update problem persists sadly, reopened in #1018
